### ISSUE TITLE
Public Access Token

### ISSUE THREAD

**Issue by thelevicole** [lauraguevara97/LIFX-Application#1]
FYI I have just been looking at your project and found that your LIFX Cloud access token is hard-coded into [`light_logic.py` on line 6](https://github.com/lauraguevara97/LIFX-Application/blob/eddc9694bdfda704a38bf52672a0ae0c6877160f/light_logic.py#L6)

A quick test shows this access token is still active and can still access your devices. I would suggest revoking access via your [account settings](https://cloud.lifx.com/settings).

**Comment by laura-swe** [comment]
Thanks! I disabled the public token
